In [2]:
!pip install natsort

In [0]:
# HTTP
from requests import get

# OS and IO
from io import BytesIO
import os
import shutil
import glob
from pathlib import Path

# Unzipping
from zipfile import ZipFile

# Science and shi*
import scipy
import matplotlib.pyplot as plt
import numpy as np

# For sorting files
from natsort import natsorted

# Read files in order
request = get('http://www.cl.cam.ac.uk/Research/DTG/attarchive/pub/data/att_faces.zip')
zip_file = ZipFile(BytesIO(request.content))
files = zip_file.namelist()
files = natsorted(files)
zip_file.extractall()

# Images to training and test data matrices:
y = np.arange(40).reshape(40, 1)
ytest = y[1::2, ::]
ytraining = y[0::2, ::]

D = np.array(np.empty([0, 10304]))
for f in files:
    if f.endswith(".pgm"):
        arr = scipy.misc.imread(f)
        # The array is transposed because I checked its dimensions and they were 112X92
        arr = arr.T
        D = np.vstack((D, arr.flatten()))
Dtest = D[1::2, ::]
Dtraining = D[0::2, ::]


# 200 training examples with 10304 feature/pixel
assert Dtraining.shape == (200, 10304)

# 200 test examples with 10304 feature/pixel
assert Dtest.shape == (200, 10304)

In [48]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target
clf = LDA()
clf.fit(X, Y)
# eigen vectors
clf.scalings_
#np.unique(iris.target)


array([[ 0.81926852,  0.03285975],
       [ 1.5478732 ,  2.15471106],
       [-2.18494056, -0.93024679],
       [-2.85385002,  2.8060046 ]])

In [102]:
Xtest = X[1::2, ::]
Xtraining = X[0::2, ::]
Ytest = Y[1::2]
Ytraining = Y[0::2]
iris_means = np.array(np.empty([0, 4]))
for i in range(0, 150, 50):
    user = X[i:i+50:, ::]
    iris_mean = np.mean(user, axis=0)
    iris_means = np.vstack((iris_means, iris_mean))
iris_mean_sample = np.mean(X, axis=0)

iris_n = iris_means.shape[0]
overall_mean = np.mean(X, axis=0)
iris_B = np.zeros((4,4))
for i in range(0, 3): 
    overall_mean = overall_mean.reshape(4,1) 
    mean_vec = iris_means[i].reshape(4,1)
    iris_B += 50 * (mean_vec - overall_mean).dot((mean_vec - overall_mean).T)
    i += 1
iris_Z = np.array(np.empty([0, 4]))
j = 0
for i in range(0, 150, 50):
    user = X[i:i+50:, ::]
    iris_Z = np.vstack((iris_Z, user-iris_means[j].T))
    j += 1
    
iris_S = iris_Z.T.dot(iris_Z)
iris_S_inverse = np.linalg.inv(iris_S)
iris_S_inverse_B = iris_S_inverse.dot(iris_B)
eigen_values, eigen_vectors = np.linalg.eig(iris_S_inverse_B)
print(eigen_vectors)


[[ 0.20490976 -0.00898234  0.68226001 -0.142006  ]
 [ 0.38714331 -0.58899857 -0.44093159  0.38002784]
 [-0.54648218  0.25428655 -0.46521433  0.44439255]
 [-0.71378517 -0.76703217  0.35167633 -0.7987042 ]]


In [4]:
means = np.array(np.empty([0, 10304]))
for i in range(0, 200, 5):
    user = Dtraining[i:i+5:, ::]
    mean = np.mean(user, axis=0)
    means = np.vstack((means, mean))
    
mean_sample = Dtraining.mean()
print(means.shape)
n = means.shape[0]
#Because python returns mean vector as row not column vector, therefore we reversed the equation

Z = np.array(np.empty([0, 10304]))
j = 0
for i in range(0, 200, 5):
    user = Dtraining[i:i+5:, ::]
    Z = np.vstack((Z, user-means[j].T))
    j += 1

#This is S, we don't have to sum all Ss from 1 to 40, I tested that with an example here https://pastebin.com/TABBdB5C    
S = Z.T.dot(Z)
S_inverse = np.linalg.inv(S)
S_inverse_B = S_inverse.dot(B)


(40, 10304)


In [0]:
#U, S, V = np.linalg.svd(S_inverse_B)
#eigen_values, eigen_vectors = np.square(S), V.T
eigen_values, eigen_vectors = np.linalg.eig(S_inverse_B)
#assert eigen_vectors.shape == (10304, 10304)
U = eigen_vectors[:, (0, 39)]
print(U.shape)

#project_trainning = Dtrainning.dot(U)
#project_test = Dtest.dot(U)