In [122]:
# HTTP
from requests import get

# OS and IO
from io import BytesIO
import os
import shutil
import glob
from pathlib import Path

# Unzipping
from zipfile import ZipFile

# Actual thing
import scipy
import matplotlib.pyplot as plt

# For sorting files
from natsort import natsorted

# Numpy
import numpy as np

request = get('http://www.cl.cam.ac.uk/Research/DTG/attarchive/pub/data/att_faces.zip')
zip_file = ZipFile(BytesIO(request.content))
files = zip_file.namelist()
files = natsorted(files)
zip_file.extractall()

dir_path = os.getcwd()

#pathlist = Path(dir_path).glob('**/*.pgm')
#for path in pathlist:
 #   path_in_str = str(path)
  #  print(path_in_str)

# BUGGYYY
#images = [path for path in pathlist]
#images = sorted(images, key=lambda x: str(x))

#print(images)

# Reading the first file in the zip file:
#zip_file.read(files[0])
# sorted_files = sorted(files)

# Because the matrix is at first empty, we append the first instance, afterwards we push the images vertically
# The array is transposed because I checked its dimensions and they were 112X92
flag = 0
y = np.arange(40).reshape(40, 1)
D = np.array([[]])
for f in files:
    if f.endswith(".pgm"):
        arr = scipy.misc.imread(f)
        arr = arr.T
        if flag == 0:
            D = np.append(D,arr.flatten())
            flag = 1
        else:
            D = np.vstack((D, arr.flatten()))
print(D.shape)
print(D)


[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]]
(400, 10304)
[[ 48.  45.  45. ...  46.  47.  46.]
 [ 60.  58.  68. ...  33.  31.  34.]
 [ 39.  44.  59. ...  28.  27.  29.]
 ...
 [125. 121. 122. ...  43.  35.  40.]
 [119. 118. 120. ...  88.  92.  85.]
 [125. 124. 121. ...  35.  32.  34.]]
