In [17]:
# HTTP
from requests import get

# OS and IO
from io import BytesIO
import os
import shutil
import glob
from pathlib import Path

# Unzipping
from zipfile import ZipFile

# Actual thing
import scipy
import matplotlib.pyplot as plt

# For sorting files
from natsort import natsorted

# Numpy
import numpy as np

request = get('http://www.cl.cam.ac.uk/Research/DTG/attarchive/pub/data/att_faces.zip')
zip_file = ZipFile(BytesIO(request.content))
files = zip_file.namelist()
files = natsorted(files)
zip_file.extractall()

dir_path = os.getcwd()

#pathlist = Path(dir_path).glob('**/*.pgm')
#for path in pathlist:
 #   path_in_str = str(path)
  #  print(path_in_str)

# BUGGYYY
#images = [path for path in pathlist]
#images = sorted(images, key=lambda x: str(x))

#print(images)

# Reading the first file in the zip file:
#zip_file.read(files[0])
# sorted_files = sorted(files)

# Because the matrix is at first empty, we append the first instance, afterwards we push the images vertically, I think we can do it in a cleaner way but i'm a bit lazy now
# The array is transposed because I checked its dimensions and they were 112X92
flag = 0
y = np.arange(40).reshape(40, 1)
ytest = y[1::2, ::]
ytrainning = y[0::2, ::]
D = np.array([[]])
for f in files:
    if f.endswith(".pgm"):
        arr = scipy.misc.imread(f)
        arr = arr.T
        if flag == 0:
            D = np.append(D,arr.flatten())
            flag = 1
        else:
            D = np.vstack((D, arr.flatten()))
Dtest = np.copy(D[1::2, ::])
Dtrainning = D[0::2, ::]



[[ 48.  45.  45. ...  46.  47.  46.]
 [ 39.  44.  59. ...  28.  27.  29.]
 [ 64.  60.  63. ...  35.  42.  39.]
 ...
 [128. 129. 126. ...  90.  91.  84.]
 [129. 130. 127. ...  95.  92.  93.]
 [119. 118. 120. ...  88.  92.  85.]]
[[ 60.  58.  68. ...  33.  31.  34.]
 [ 63.  56.  52. ...  25.  28.  24.]
 [ 43.  45.  57. ... 175. 174. 169.]
 ...
 [123. 128. 126. ...  44.  39.  42.]
 [125. 121. 122. ...  43.  35.  40.]
 [125. 124. 121. ...  35.  32.  34.]]
